# Generated by Django 6.0.1 on 2026-01-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_procedure_image_alter_salon_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='experience',
            field=models.TextField(blank=True, verbose_name='Стаж работы'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Специальность'),
        ),
    ]
