# Generated by Django 6.0.1 on 2026-01-21 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_specialist_experience_alter_specialist_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='procedures/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Фото услуги'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='specialists/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Фото мастера'),
        ),
    ]
