# Generated by Django 6.0.1 on 2026-01-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_procedure_image_alter_specialist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='question',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Вопрос'),
        ),
    ]
