# Generated by Django 6.0.1 on 2026-01-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID платежа'),
        ),
    ]
