# Generated by Django 6.0.1 on 2026-01-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='procedures',
            field=models.ManyToManyField(blank=True, related_name='specialists', to='core.procedure', verbose_name='Какие услуги делает'),
        ),
    ]
