# Generated by Django 6.0.1 on 2026-01-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_booking_id_alter_consentacceptance_id_and_more'),
        ('core', '0006_specialist_procedures'),
    ]

    operations = [
    ]
