# Generated by Django 6.0.1 on 2026-01-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_payment_id'),
        ('core', '0008_alter_booking_id_alter_consentacceptance_id_and_more'),
    ]

    operations = [
    ]
